### PR TITLE
Add support of GDPR

### PR DESCRIPTION
**Pull request by PWyrembak**
Hi, review please our changes and if all is correct please merge it in your repository to support GDPR for TrustX adapter.

### CODE REVIEW

**Comment by ix-certification** [comment]
Hi,

We are seeing rebase issues with this branch as it looks like it wasn't based off master-v2 originally. Can you please rebase the changes against master-v2 so that we can confirm the proper changes?

Thanks

**Comment by PWyrembak** [comment]
+ TrustX support for visibility



PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>




-------- Original message --------

**Comment by PWyrembak** [comment]
Rebased, review please.

**Comment by ix-certification** [comment]
Hi Paul,

Unfortunately I'm still seeing issues with the PR in that github is stating that there are conflicts against the master-v2 branch:

`This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.`

I would recommend ensuring that you are rebasing against a clean branch of master-v2 or directly against the origin to ensure that all changes are properly captured.

Thanks

**Comment by PWyrembak** [comment]
Looping in Alexandra and Mike.



PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>




-------- Original message --------

**Comment by PWyrembak** [comment]
Hello IX team, we did a rebase, please check, now all must be right

**Comment by PWyrembak** [comment]
Hi IX Team,

Can you please check our latest update to the pull request we made?  We have not yet received any feedback.

https://github.com/indexexchange/trust-x-adapter/pull/4

Best,
Paul

PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Comment by ix-certification** [comment]
Hi Paul,

Would it be possible to setup a call so we can walkthrough together the rebase and merge of your code? Github is still complaining about not being able to merge in anything to master-v2 as they have detected conflicts. 

We'd be free early next week - would anytime on Tuesday or Wednesday between 10am and 1pm work for you?

Thanks

**Comment by PWyrembak** [comment]
+Mike and Alexandra

Could we please schedule 11am ET on Tuesday (6/5) for this call?

Thanks,
Paul

PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Comment by ix-certification** [comment]
Hi Paul,

I've sent over an invite for the walkthrough next week on Tuesday (6/5) at 11am ET.

Let me know if there's anyone else you'd like me to add to the invite.

Thanks

**Comment by PWyrembak** [comment]
Please add Alexandra and Mike to the invitation.

Mike Pugh <mpugh@iponweb.net>

Alexandra Balashoyu <abalashoyu@iponweb.net>



PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>




-------- Original message --------

**Comment by PWyrembak** [comment]
Hi IX Team,
Please create a new clean branch of master-v2 we could put our changes to.
Would be great if we could do this before the call.

Could you also add one more participant to the invitation?
Vasily Bratchuk <vbratchuk@iponweb.net>

**Comment by PWyrembak** [comment]
IX Team,

Thanks for jumping on the call with us yesterday. We have resubmitted changes as requested. Please let me know if it looks okay.

https://github.com/indexexchange/trust-x-adapter/pull/5





PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>




-------- Original message --------

**Pull request closed without merging**
