### PR TITLE
Added GDPR support

### PR DESCRIPTION
**Pull request by PWyrembak**
Hi IX Team, 
Review please our changes and if all is correct please merge it in your repository to support GDPR for TrustX adapter.

### CODE REVIEW

**Comment by ix-certification** [comment]
Hi Paul,

The code looks good and we've tested the changes and are able to see the consent string being passed to your endpoint. You can verify the changes here: http://sandbox.ht.indexexchange.com/ht/adapter-test-page.html by redirecting the following file : https://sandbox.ht.indexexchange.com/ht/placeholder.js to use http://sandbox.ht.indexexchange.com/ht/trust-x-adapter-wrapper.js. You can expect to see the GDPR consent flag enabled and the consent string passed to your endpoint. 

Just one note - in your previous PR there were some changes to the sync pixel which I'm not seeing here. Can you confirm those changes are not needed?

Once everything looks good on your end, we'll be good to merge the code here :)

Thanks,
IX

**Comment by ix-certification** [comment]
Hi Paul,

Have you guys gotten the chance to review the test page above with your changes to confirm it is what your endpoint expects?

Thanks,
IX

**Comment by PWyrembak** [comment]
Hi Guys,

Apologies on the delay.  Our MSK team has been OOO yesterday and today due to holiday.  I hope to have confirmation for you before end of the week.

Thanks,
Paul

PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Comment by PWyrembak** [comment]
Hi IX Team,

Confirming that the changes look good to us and are what was expected.  Please go ahead and merge the code at your convenience.

Best,
Paul

PAUL WYREMBAK
TrustX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Pull request merged**
